// architex is a DevSecOps CLI that parses Terraform, builds an architecture
// graph, computes deltas between graph versions, and evaluates architectural
// risk. Subcommands:
//
//	architex graph    <dir>                 -- build and print the graph for one dir
//	architex diff     <base-dir> <head-dir> -- print the semantic delta between two graphs
//	architex score    <base-dir> <head-dir> -- print the risk evaluation of the delta
//	architex report   <base-dir> <head-dir> -- print the full PR-ready Markdown payload
//	architex sanitize <base-dir> <head-dir> -- print the sanitized egress payload (JSON)
//	architex comment  <bundle-dir>          -- upsert the bundle's summary.md as a sticky PR comment
//
// Stdout: machine-readable artifact (JSON for graph/diff/score/sanitize, Markdown for report).
// Stderr: human-readable progress + warnings, prefixed with "[architex]".
//
// The `comment` subcommand is the ONLY architex command that performs
// outbound network I/O. The analysis pipeline (parser/graph/delta/risk/
// interpreter) never touches the network.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"architex/baseline"
	"architex/config"
	"architex/delta"
	gh "architex/github"
	"architex/graph"
	"architex/interpreter"
	"architex/models"
	"architex/parser"
	"architex/risk"
)

const usage = `architex -- DevSecOps architecture graph + risk CLI

Usage:
  architex graph    <dir>
  architex diff     <base-dir> <head-dir>
  architex score    <base-dir> <head-dir>
  architex report   <base-dir> <head-dir> [--out <dir>] [--salt <salt>]
  architex sanitize <base-dir> <head-dir> [--salt <salt>]
  architex baseline <dir> [--out <path>] [--merge]
  architex comment  <bundle-dir> --repo <owner/repo> --pr <num> [--mode advisory|blocking] [--token-env GITHUB_TOKEN]
`

// stickyMarker is the substring used to find an existing ArchiteX PR comment
// for in-place updates. It MUST match the footer emitted by
// interpreter.FormatMarkdown -- if the formatter changes, change this too
// (and keep the formatter as the single source of truth in summary.md).
const stickyMarker = "_Generated by ArchiteX (deterministic mode)._"

// commentBodyBudget is the upper bound (in bytes) of the comment body we will
// POST to GitHub. GitHub stores issue/PR comments in a MySQL `mediumblob`
// column with a 262,144-byte hard limit; community/27190 documents this and
// users have empirically posted comments up to ~200 KB. We leave a 22 KB
// safety margin so that any incidental UTF-8 byte expansion or a slightly
// oversized body never trips the API. Defense-in-depth -- the diagram
// density cap (interpreter.MermaidBudget) handles the much-more-common
// mermaid-renderer cliff.
const commentBodyBudget = 240_000

func main() {
	if len(os.Args) < 2 {
		fmt.Fprint(os.Stderr, usage)
		os.Exit(2)
	}

	switch os.Args[1] {
	case "graph":
		os.Exit(runGraph(os.Args[2:]))
	case "diff":
		os.Exit(runDiff(os.Args[2:]))
	case "score":
		os.Exit(runScore(os.Args[2:]))
	case "report":
		os.Exit(runReport(os.Args[2:]))
	case "sanitize":
		os.Exit(runSanitize(os.Args[2:]))
	case "baseline":
		os.Exit(runBaseline(os.Args[2:]))
	case "comment":
		os.Exit(runComment(os.Args[2:]))
	case "-h", "--help", "help":
		fmt.Fprint(os.Stdout, usage)
		os.Exit(0)
	default:
		fmt.Fprintf(os.Stderr, "unknown subcommand %q\n\n%s", os.Args[1], usage)
		os.Exit(2)
	}
}

func runGraph(args []string) int {
	if len(args) != 1 {
		fmt.Fprintln(os.Stderr, "usage: architex graph <dir>")
		return 2
	}
	cfg := loadConfigForDir(args[0])
	g, err := buildGraphWith(args[0], cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error: %v\n", err)
		return 1
	}
	return writeJSON(os.Stdout, g)
}

func runDiff(args []string) int {
	if len(args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: architex diff <base-dir> <head-dir>")
		return 2
	}
	cfg := loadConfigForDir(args[1])
	base, head, code := buildBaseHeadWith(args[0], args[1], cfg)
	if code != 0 {
		return code
	}
	d := delta.Compare(base, head)
	fmt.Fprintf(os.Stderr, "[architex] delta: %s\n", delta.HumanSummary(d))
	return writeJSON(os.Stdout, d)
}

func runScore(args []string) int {
	if len(args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: architex score <base-dir> <head-dir>")
		return 2
	}
	cfg := loadConfigForDir(args[1])
	bl := loadBaselineForDir(args[1])
	base, head, code := buildBaseHeadWith(args[0], args[1], cfg)
	if code != 0 {
		return code
	}
	d := delta.Compare(base, head)
	result := risk.EvaluateWithBaseline(d, cfg, bl, time.Now())

	fmt.Fprintf(os.Stderr, "[architex] delta: %s\n", delta.HumanSummary(d))
	logRisk(result)
	return writeJSON(os.Stdout, result)
}

func runReport(args []string) int {
	fs := flag.NewFlagSet("report", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	out := fs.String("out", "", "directory to write audit bundle into (timestamped subdir)")
	salt := fs.String("salt", "", "salt for sanitization hashing in audit egress.json")
	flagArgs, positional := splitFlagsAndPositional(args)
	if err := fs.Parse(flagArgs); err != nil {
		return 2
	}
	rest := positional
	if len(rest) != 2 {
		fmt.Fprintln(os.Stderr, "usage: architex report <base-dir> <head-dir> [--out <dir>] [--salt <salt>]")
		return 2
	}

	cfg := loadConfigForDir(rest[1])
	bl := loadBaselineForDir(rest[1])
	base, head, code := buildBaseHeadWith(rest[0], rest[1], cfg)
	if code != 0 {
		return code
	}
	d := delta.Compare(base, head)
	result := risk.EvaluateWithBaseline(d, cfg, bl, time.Now())
	rep := interpreter.Render(d, result, nil)

	logRisk(result)

	if *out != "" {
		bundle, err := interpreter.WriteAudit(rep, interpreter.AuditOptions{
			OutDir:   *out,
			BaseDir:  rest[0],
			HeadDir:  rest[1],
			HashSalt: *salt,
		})
		if err != nil {
			fmt.Fprintf(os.Stderr, "[architex] audit error: %v\n", err)
			return 1
		}
		fmt.Fprintf(os.Stderr, "[architex] audit bundle: %s\n", bundle.Path)
	}

	if _, err := io.WriteString(os.Stdout, interpreter.FormatMarkdown(rep)); err != nil {
		fmt.Fprintf(os.Stderr, "[architex] write error: %v\n", err)
		return 1
	}
	return 0
}

func runSanitize(args []string) int {
	fs := flag.NewFlagSet("sanitize", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	salt := fs.String("salt", "", "salt for sanitization hashing")
	flagArgs, positional := splitFlagsAndPositional(args)
	if err := fs.Parse(flagArgs); err != nil {
		return 2
	}
	rest := positional
	if len(rest) != 2 {
		fmt.Fprintln(os.Stderr, "usage: architex sanitize <base-dir> <head-dir> [--salt <salt>]")
		return 2
	}

	cfg := loadConfigForDir(rest[1])
	bl := loadBaselineForDir(rest[1])
	base, head, code := buildBaseHeadWith(rest[0], rest[1], cfg)
	if code != 0 {
		return code
	}
	d := delta.Compare(base, head)
	result := risk.EvaluateWithBaseline(d, cfg, bl, time.Now())
	rep := interpreter.Render(d, result, nil)
	payload := interpreter.Sanitize(rep, interpreter.SanitizationPolicy{HashSalt: *salt})

	fmt.Fprintf(os.Stderr, "[architex] egress payload schema=%s severity=%s status=%s\n",
		payload.SchemaVersion, payload.Severity, payload.Status)
	return writeJSON(os.Stdout, payload)
}

// runBaseline writes (or extends) a `.architex/baseline.json` snapshot of a
// directory's current architecture graph. Used to enable the Phase 7 PR5
// `first_time_*` anomaly rules. Without `--merge` the file is replaced by
// the current snapshot; with `--merge` the existing file is loaded and the
// current snapshot is unioned into it (so a sweep across multiple stacks
// can incrementally build a single baseline). The output path defaults to
// `<dir>/.architex/baseline.json`.
func runBaseline(args []string) int {
	fs := flag.NewFlagSet("baseline", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	out := fs.String("out", "", "explicit output path (default: <dir>/.architex/baseline.json)")
	merge := fs.Bool("merge", false, "union with the existing baseline at --out instead of replacing it")
	flagArgs, positional := splitFlagsAndPositional(args)
	if err := fs.Parse(flagArgs); err != nil {
		return 2
	}
	if len(positional) != 1 {
		fmt.Fprintln(os.Stderr, "usage: architex baseline <dir> [--out <path>] [--merge]")
		return 2
	}
	dir := positional[0]
	outPath := *out
	if outPath == "" {
		outPath = filepath.Join(dir, baseline.FileName)
	}

	cfg := loadConfigForDir(dir)
	g, err := buildGraphWith(dir, cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error: %v\n", err)
		return 1
	}

	snap := baseline.FromGraph(g, time.Now())
	if *merge {
		existing, err := baseline.Load(outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "[architex] WARN baseline merge: %v -- writing fresh snapshot\n", err)
		} else if existing != nil {
			snap = baseline.Merge(existing, snap)
			snap.GeneratedAt = time.Now().UTC()
		}
	}

	if err := baseline.Save(outPath, snap); err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error: %v\n", err)
		return 1
	}
	fmt.Fprintf(os.Stderr,
		"[architex] baseline written: %s (%d provider types, %d abstract types, %d edge pairs)\n",
		outPath, len(snap.ProviderTypes), len(snap.AbstractTypes), len(snap.EdgePairs))
	return 0
}

// runComment posts (or updates) the bundle's summary.md as a sticky PR
// comment on GitHub. The bundle directory must contain both `summary.md`
// (the comment body) and `score.json` (read to decide blocking-mode exit).
//
// Exit semantics:
//   - mode=advisory (default): always exit 0 if the post succeeded, even
//     when risk.Status == "fail". Use this for the §11 Phase 1/2 rollout.
//   - mode=blocking: exit 1 when risk.Status == "fail", exit 0 otherwise.
//     "warn" is intentionally non-blocking (master.md §11 reserves blocking
//     for the "fail" tier).
func runComment(args []string) int {
	fs := flag.NewFlagSet("comment", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	repo := fs.String("repo", "", "GitHub repository as owner/name (required)")
	prNum := fs.Int("pr", 0, "Pull request number (required)")
	mode := fs.String("mode", "advisory", "advisory | blocking -- exit code in blocking mode reflects risk.Status==\"fail\"")
	tokenEnv := fs.String("token-env", "GITHUB_TOKEN", "environment variable holding the GitHub API token")
	dryRun := fs.Bool("dry-run", false, "print what would be sent and skip the API call")

	flagArgs, positional := splitFlagsAndPositional(args)
	if err := fs.Parse(flagArgs); err != nil {
		return 2
	}
	if len(positional) != 1 {
		fmt.Fprintln(os.Stderr, "usage: architex comment <bundle-dir> --repo <owner/repo> --pr <num> [--mode advisory|blocking]")
		return 2
	}
	bundleDir := positional[0]

	owner, repoName, ok := splitRepoSlug(*repo)
	if !ok {
		fmt.Fprintf(os.Stderr, "[architex] error: --repo must be \"owner/name\", got %q\n", *repo)
		return 2
	}
	if *prNum <= 0 {
		fmt.Fprintln(os.Stderr, "[architex] error: --pr must be a positive integer")
		return 2
	}
	if *mode != "advisory" && *mode != "blocking" {
		fmt.Fprintf(os.Stderr, "[architex] error: --mode must be \"advisory\" or \"blocking\", got %q\n", *mode)
		return 2
	}

	bodyPath := filepath.Join(bundleDir, "summary.md")
	scorePath := filepath.Join(bundleDir, "score.json")

	body, err := os.ReadFile(bodyPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error reading %s: %v\n", bodyPath, err)
		return 1
	}
	scoreRaw, err := os.ReadFile(scorePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error reading %s: %v\n", scorePath, err)
		return 1
	}
	var result risk.RiskResult
	if err := json.Unmarshal(scoreRaw, &result); err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error parsing %s: %v\n", scorePath, err)
		return 1
	}

	originalBytes := len(body)
	body = capCommentBody(body, commentBodyBudget)
	if len(body) != originalBytes {
		fmt.Fprintf(os.Stderr, "[architex] body safety net engaged: %d bytes -> %d bytes (diagram block stripped)\n",
			originalBytes, len(body))
	}

	fmt.Fprintf(os.Stderr, "[architex] sticky-upserting comment on %s/%s#%d (mode=%s, status=%s, body=%d bytes)\n",
		owner, repoName, *prNum, *mode, result.Status, len(body))

	if *dryRun {
		fmt.Fprintf(os.Stderr, "[architex] dry-run: would POST/PATCH a %d-byte body containing marker=%v\n",
			len(body), strings.Contains(string(body), stickyMarker))
	} else {
		token := os.Getenv(*tokenEnv)
		if token == "" {
			fmt.Fprintf(os.Stderr, "[architex] error: %s is empty -- pass a token via --token-env or set the env var\n", *tokenEnv)
			return 1
		}
		client := gh.New(token)
		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		defer cancel()
		comment, err := gh.UpsertStickyComment(ctx, client, owner, repoName, *prNum, stickyMarker, string(body))
		if err != nil {
			fmt.Fprintf(os.Stderr, "[architex] error: %v\n", err)
			return 1
		}
		fmt.Fprintf(os.Stderr, "[architex] comment id=%d url=%s\n", comment.ID, comment.URL)
	}

	if *mode == "blocking" && result.Status == "fail" {
		fmt.Fprintln(os.Stderr, "[architex] blocking mode: exiting 1 due to risk.Status=fail")
		return 1
	}
	return 0
}

// splitRepoSlug parses an "owner/name" repository slug.
func splitRepoSlug(slug string) (owner, name string, ok bool) {
	parts := strings.SplitN(slug, "/", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", false
	}
	return parts[0], parts[1], true
}

// capCommentBody enforces an upper byte bound on the PR-comment body. If
// body is already within budget it is returned unchanged. Otherwise the
// strategy is:
//
//  1. Locate the fenced ```mermaid ... ``` block (the largest section by far
//     for big deltas) and replace it with a one-line note pointing at the
//     audit bundle artifact.
//  2. If that already fits, return.
//  3. If still oversize (or no mermaid block existed), hard-truncate at
//     maxBytes-128 bytes and append an explicit truncation marker so the
//     comment never claims to be complete when it isn't.
//
// The note and marker are deterministic; the sticky marker (footer) MUST
// remain present in the result so the next run can find and update this
// same comment in place.
func capCommentBody(body []byte, maxBytes int) []byte {
	if maxBytes <= 0 || len(body) <= maxBytes {
		return body
	}

	const mermaidOpen = "```mermaid"
	const mermaidClose = "```"
	noticeFmt := "_Diagram omitted: rendered comment was %d bytes (over the %d-byte safety budget). Full diagram is in the ArchiteX audit bundle artifact._\n"

	if openIdx := bytes.Index(body, []byte(mermaidOpen)); openIdx >= 0 {
		closeRel := bytes.Index(body[openIdx+len(mermaidOpen):], []byte(mermaidClose))
		if closeRel >= 0 {
			closeIdx := openIdx + len(mermaidOpen) + closeRel + len(mermaidClose)
			if closeIdx < len(body) && body[closeIdx] == '\n' {
				closeIdx++
			}
			notice := []byte(fmt.Sprintf(noticeFmt, len(body), maxBytes))
			rebuilt := make([]byte, 0, len(body)-(closeIdx-openIdx)+len(notice))
			rebuilt = append(rebuilt, body[:openIdx]...)
			rebuilt = append(rebuilt, notice...)
			rebuilt = append(rebuilt, body[closeIdx:]...)
			if len(rebuilt) <= maxBytes {
				return rebuilt
			}
			body = rebuilt
		}
	}

	// Hard fallback: truncate while keeping the sticky marker so future runs
	// can still find this comment and update it in place.
	const truncationTag = "\n\n_[ArchiteX comment truncated to fit GitHub size limit -- see audit bundle artifact for the full report.]_\n" + stickyMarker + "\n"
	keep := maxBytes - len(truncationTag)
	if keep < 0 {
		keep = 0
	}
	if keep > len(body) {
		keep = len(body)
	}
	out := make([]byte, 0, keep+len(truncationTag))
	out = append(out, body[:keep]...)
	out = append(out, []byte(truncationTag)...)
	return out
}

// buildBaseHead parses both directories and returns the constructed graphs.
// On error it writes a stderr diagnostic and returns a non-zero exit code.
func buildBaseHead(baseDir, headDir string) (models.Graph, models.Graph, int) {
	return buildBaseHeadWith(baseDir, headDir, nil)
}

// buildBaseHeadWith is the configurable variant. The same cfg is applied to
// both base and head graphs; this matches the user expectation that "ignore
// path X" means "X never enters my graph", regardless of which side.
func buildBaseHeadWith(baseDir, headDir string, cfg *config.Config) (models.Graph, models.Graph, int) {
	base, err := buildGraphWith(baseDir, cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error parsing base: %v\n", err)
		return models.Graph{}, models.Graph{}, 1
	}
	head, err := buildGraphWith(headDir, cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error parsing head: %v\n", err)
		return models.Graph{}, models.Graph{}, 1
	}
	return base, head, 0
}

func logRisk(r risk.RiskResult) {
	fmt.Fprintf(os.Stderr, "[architex] risk level: %.1f/10 (higher = more risk) | severity: %s | status: %s\n",
		r.Score, r.Severity, r.Status)
	for _, reason := range r.Reasons {
		fmt.Fprintf(os.Stderr, "[architex]   [%.1f] %s -- %s\n", reason.Weight, reason.RuleID, reason.Message)
	}
}

// buildGraph parses a directory and constructs the graph, emitting parser
// warnings to stderr as a side effect.
func buildGraph(dir string) (models.Graph, error) {
	return buildGraphWith(dir, nil)
}

// buildGraphWith is the configurable variant -- a non-nil cfg is forwarded
// to the parser so ignore.paths patterns drop matching .tf files before they
// ever enter the graph.
func buildGraphWith(dir string, cfg *config.Config) (models.Graph, error) {
	resources, warnings, err := parser.ParseDirWith(dir, cfg)
	if err != nil {
		return models.Graph{}, err
	}
	for _, w := range warnings {
		fmt.Fprintf(os.Stderr, "[architex] WARN [%s]: %s\n", w.Category, w.Message)
	}
	return graph.Build(resources, warnings), nil
}

// loadConfigForDir loads `.architex.yml` from dir (no error if absent), then
// merges any inline `# architex:ignore=...` directives discovered in the same
// directory tree. A returned nil *Config means "no config" -- callers must
// behave identically to a v1.1 run in that case.
//
// Errors are emitted to stderr but never abort the run; a malformed config
// file degrades to "no config" so a typo cannot brick CI.
func loadConfigForDir(dir string) *config.Config {
	cfgPath := filepath.Join(dir, config.FileName)
	cfg, err := config.Load(cfgPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[architex] WARN config: %v -- continuing with defaults\n", err)
		return nil
	}
	inline, err := config.ScanInlineSuppressions(dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[architex] WARN config: inline scan: %v\n", err)
	}
	if cfg == nil && len(inline) == 0 {
		return nil
	}
	if cfg == nil {
		cfg = &config.Config{}
	}
	cfg.Add(inline...)
	fmt.Fprintf(os.Stderr, "[architex] config: loaded (%d rule overrides, %d ignore paths, %d suppressions)\n",
		len(cfg.Rules), len(cfg.Ignore.Paths), len(cfg.Suppressions))
	return cfg
}

// loadBaselineForDir loads `.architex/baseline.json` from `dir` (no error
// if absent), returning nil when no baseline is present so the caller's
// `first_time_*` rules stay silent. A malformed baseline is treated as
// "no baseline" with a stderr warning, matching the loadConfigForDir
// degradation policy: a typo in baseline.json must never brick CI.
func loadBaselineForDir(dir string) *baseline.Baseline {
	path := filepath.Join(dir, baseline.FileName)
	bl, err := baseline.Load(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[architex] WARN baseline: %v -- continuing without baseline rules\n", err)
		return nil
	}
	if bl == nil {
		return nil
	}
	fmt.Fprintf(os.Stderr,
		"[architex] baseline: loaded %s (%d provider types, %d abstract types, %d edge pairs)\n",
		path, len(bl.ProviderTypes), len(bl.AbstractTypes), len(bl.EdgePairs))
	return bl
}

// splitFlagsAndPositional separates an arg slice into flag args (anything
// starting with "-" plus its value when not "=" separated) and positional
// args. This lets users put flags before OR after positionals on the CLI,
// which is friendlier than Go's default flag-parser behavior.
//
// Recognized as a flag value-pair when the flag does not contain "=" and the
// next arg does not start with "-".
func splitFlagsAndPositional(args []string) (flags []string, positional []string) {
	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case a == "--":
			positional = append(positional, args[i+1:]...)
			return
		case len(a) > 1 && a[0] == '-':
			flags = append(flags, a)
			if !contains(a, '=') && i+1 < len(args) {
				next := args[i+1]
				if len(next) == 0 || next[0] != '-' {
					flags = append(flags, next)
					i++
				}
			}
		default:
			positional = append(positional, a)
		}
	}
	return
}

func contains(s string, c byte) bool {
	for i := 0; i < len(s); i++ {
		if s[i] == c {
			return true
		}
	}
	return false
}

func writeJSON(w io.Writer, v any) int {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error encoding JSON: %v\n", err)
		return 1
	}
	return 0
}
