// Package golden contains the byte-identical snapshot harness for the
// readability refactor (see master.md / .cursor/plans/architex_readability_*).
//
// For each example under <repo>/examples/<name>/{base,head} this test runs
// the full ArchiteX pipeline (parser -> graph -> delta -> risk -> interpreter)
// the same way `architex report` does, captures the three timestamp-free
// artifacts that make up the PR-visible contract -- summary.md, score.json,
// egress.json -- and asserts each one is byte-identical to the snapshot
// recorded under <repo>/testdata/golden/<name>/.
//
// The snapshot is regenerated by setting the env var ARCHITEX_GOLDEN_UPDATE=1
// before `go test`. When updating, every refactor PR MUST verify the
// snapshot does not actually change before committing -- the whole point
// of this harness is that PRs in the readability series produce zero output
// drift. A snapshot diff on a non-PR0 PR is a refactor regression, not a
// "go ahead and update".
//
// Notes on what is NOT snapshotted (intentional):
//
//   - report.html: contains the audit Manifest with a wall-clock timestamp.
//     The HTML rendering path is exercised by interpreter/html_test.go.
//   - manifest.json: same reason.
//   - bundle directory name: built from a wall-clock stamp.
//
// summary.md / score.json / egress.json are intentionally the ONLY files
// we lock here because they are the actual user-visible surface (the PR
// comment, the score JSON consumed by `architex comment` blocking mode,
// and the sanitized egress payload that may leave the runner). If those
// three stay byte-identical across a refactor, the user-facing behavior
// is identical.
//
// The harness lives under internal/golden/ (rather than the repo root)
// so that the repo root has no Go code post-PR1; cmd/architex/ is the
// canonical binary entrypoint. Paths are resolved relative to the repo
// root via repoRoot() rather than the package directory so the test stays
// runnable from `go test ./...` invoked anywhere.
package golden

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"architex/baseline"
	"architex/config"
	"architex/delta"
	"architex/graph"
	"architex/interpreter"
	"architex/models"
	"architex/parser"
	"architex/risk"

	// Blank-import the rules aggregator so the registry is populated
	// before TestGolden_* runs. Mirrors the wiring in
	// cmd/architex/main.go; see architex/risk/rules/rules.go for the
	// rationale on why the risk package itself does not import this.
	_ "architex/risk/rules"
)

// goldenExamples is the closed list of fixture pairs the harness locks. It
// mirrors the seven cases enumerated in .github/workflows/architex.yml's
// "Examples gallery regression" step so the two stay in lockstep.
var goldenExamples = []string{
	"01-public-alb",
	"02-eks-public-endpoint",
	"03-iam-admin-attachment",
	"04-cloudfront-no-waf",
	"05-library-mode",
	"06-lambda-public-url",
	"07-azure-public-lb",
}

// goldenArtifacts is the set of byte-locked artifacts per example. Order
// matters only for stable test failure messages.
var goldenArtifacts = []string{"summary.md", "score.json", "egress.json"}

// fixedClock is the wall-clock value used everywhere in the harness so any
// time-dependent suppression-expiry path stays deterministic. The current
// example fixtures do not use suppressions with expiries, but freezing the
// clock makes the harness immune to a future fixture that does.
var fixedClock = time.Date(2026, 4, 22, 12, 0, 0, 0, time.UTC)

func TestGolden_ExamplesAreByteIdentical(t *testing.T) {
	update := os.Getenv("ARCHITEX_GOLDEN_UPDATE") == "1"
	root := repoRoot(t)

	for _, name := range goldenExamples {
		t.Run(name, func(t *testing.T) {
			baseDir := filepath.Join(root, "examples", name, "base")
			headDir := filepath.Join(root, "examples", name, "head")

			artifacts, err := renderExample(baseDir, headDir)
			if err != nil {
				t.Fatalf("render %s: %v", name, err)
			}

			goldenDir := filepath.Join(root, "testdata", "golden", name)
			if update {
				if err := os.MkdirAll(goldenDir, 0o755); err != nil {
					t.Fatalf("mkdir golden: %v", err)
				}
				for _, art := range goldenArtifacts {
					path := filepath.Join(goldenDir, art)
					if err := os.WriteFile(path, artifacts[art], 0o644); err != nil {
						t.Fatalf("write golden %s: %v", path, err)
					}
				}
				return
			}

			for _, art := range goldenArtifacts {
				path := filepath.Join(goldenDir, art)
				want, err := os.ReadFile(path)
				if err != nil {
					t.Fatalf("read golden %s: %v (run with ARCHITEX_GOLDEN_UPDATE=1 to create)", path, err)
				}
				got := artifacts[art]
				if !bytes.Equal(want, got) {
					t.Errorf("%s/%s drifted from golden\n--- want (%d bytes)\n%s\n--- got (%d bytes)\n%s",
						name, art, len(want), trimForLog(want), len(got), trimForLog(got))
				}
			}
		})
	}
}

// renderExample runs the same pipeline as `architex report` (see
// internal/cli/report.go) and returns the three byte-locked artifacts. It
// deliberately uses the public package APIs only -- if a refactor changes a
// public signature the harness fails to compile, which is the right kind
// of failure.
func renderExample(baseDir, headDir string) (map[string][]byte, error) {
	cfg, err := loadGoldenConfig(headDir)
	if err != nil {
		return nil, fmt.Errorf("config: %w", err)
	}
	bl, err := baseline.Load(filepath.Join(headDir, baseline.FileName))
	if err != nil {
		return nil, fmt.Errorf("baseline: %w", err)
	}

	base, err := buildGoldenGraph(baseDir, cfg)
	if err != nil {
		return nil, fmt.Errorf("base graph: %w", err)
	}
	head, err := buildGoldenGraph(headDir, cfg)
	if err != nil {
		return nil, fmt.Errorf("head graph: %w", err)
	}

	d := delta.Compare(base, head)
	result := risk.EvaluateWithBaseline(d, cfg, bl, fixedClock)
	rep := interpreter.RenderWithGraph(d, result, head, nil)

	summary := []byte(interpreter.FormatMarkdown(rep))

	scoreJSON, err := json.MarshalIndent(rep.Risk, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal score: %w", err)
	}
	scoreJSON = append(scoreJSON, '\n')

	egress := interpreter.Sanitize(rep, interpreter.SanitizationPolicy{})
	egressJSON, err := json.MarshalIndent(egress, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal egress: %w", err)
	}
	egressJSON = append(egressJSON, '\n')

	return map[string][]byte{
		"summary.md":  summary,
		"score.json":  scoreJSON,
		"egress.json": egressJSON,
	}, nil
}

// loadGoldenConfig is the harness equivalent of cli.loadConfigForDir but
// without the stderr side effects. It reads .architex.yml plus inline
// suppressions exactly the same way production does, so library-mode
// (example 05) and any future config-driven example get the same handling
// they would in CI.
func loadGoldenConfig(dir string) (*config.Config, error) {
	cfg, err := config.Load(filepath.Join(dir, config.FileName))
	if err != nil {
		return nil, err
	}
	inline, err := config.ScanInlineSuppressions(dir)
	if err != nil {
		return nil, err
	}
	if cfg == nil && len(inline) == 0 {
		return nil, nil
	}
	if cfg == nil {
		cfg = &config.Config{}
	}
	cfg.Add(inline...)
	return cfg, nil
}

// buildGoldenGraph is the harness equivalent of cli.buildGraphWith. It
// matches production exactly -- warnings flow into graph.Confidence
// verbatim, no sorting -- so the snapshot reflects whatever the production
// pipeline would produce. Warnings happen not to appear in any of the
// three snapshotted artifacts (they are part of the graph, not the
// RiskResult / Delta / EgressPayload), but matching production is the
// safe default.
func buildGoldenGraph(dir string, cfg *config.Config) (models.Graph, error) {
	resources, warnings, err := parser.ParseDirWith(dir, cfg)
	if err != nil {
		return models.Graph{}, err
	}
	return graph.Build(resources, warnings), nil
}

// repoRoot returns the absolute path of the repository root. The harness
// lives at <repo>/internal/golden/ so the root is two levels up from this
// source file; runtime.Caller is used so the result is independent of the
// caller's working directory.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatalf("runtime.Caller failed -- cannot resolve repo root")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", ".."))
}

// trimForLog keeps test failure messages readable when a snapshot drifts.
// First 1 KB is enough to pinpoint the diff; pair this with a `git diff
// testdata/golden/` for the full picture.
func trimForLog(b []byte) string {
	const max = 1024
	if len(b) <= max {
		return string(b)
	}
	return string(b[:max]) + "\n...[truncated]..."
}
