package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	gh "architex/github"
	"architex/risk"
)

// stickyMarker is the substring used to find an existing ArchiteX PR
// comment for in-place updates. It MUST match the footer emitted by
// interpreter.FormatMarkdown -- if the formatter changes, change this too
// (and keep the formatter as the single source of truth in summary.md).
const stickyMarker = "_Generated by ArchiteX (deterministic mode)._"

// commentBodyBudget is the upper bound (in bytes) of the comment body we
// will POST to GitHub. GitHub stores issue/PR comments in a MySQL
// `mediumblob` column with a 262,144-byte hard limit; community/27190
// documents this and users have empirically posted comments up to ~200 KB.
// We leave a 22 KB safety margin so that any incidental UTF-8 byte
// expansion or a slightly oversized body never trips the API.
// Defense-in-depth -- the diagram density cap (interpreter.MermaidBudget)
// handles the much-more-common mermaid-renderer cliff.
const commentBodyBudget = 240_000

// RunComment posts (or updates) the bundle's summary.md as a sticky PR
// comment on GitHub. The bundle directory must contain both `summary.md`
// (the comment body) and `score.json` (read to decide blocking-mode exit).
//
// Exit semantics:
//   - mode=advisory (default): always exit 0 if the post succeeded, even
//     when risk.Status == "fail". Use this for the §11 Phase 1/2 rollout.
//   - mode=blocking: exit 1 when risk.Status == "fail", exit 0 otherwise.
//     "warn" is intentionally non-blocking (master.md §11 reserves blocking
//     for the "fail" tier).
func RunComment(args []string) int {
	fs := flag.NewFlagSet("comment", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	repo := fs.String("repo", "", "GitHub repository as owner/name (required)")
	prNum := fs.Int("pr", 0, "Pull request number (required)")
	mode := fs.String("mode", "advisory", "advisory | blocking -- exit code in blocking mode reflects risk.Status==\"fail\"")
	tokenEnv := fs.String("token-env", "GITHUB_TOKEN", "environment variable holding the GitHub API token")
	dryRun := fs.Bool("dry-run", false, "print what would be sent and skip the API call")

	flagArgs, positional := splitFlagsAndPositional(args)
	if err := fs.Parse(flagArgs); err != nil {
		return 2
	}
	if len(positional) != 1 {
		fmt.Fprintln(os.Stderr, "usage: architex comment <bundle-dir> --repo <owner/repo> --pr <num> [--mode advisory|blocking]")
		return 2
	}
	bundleDir := positional[0]

	owner, repoName, ok := splitRepoSlug(*repo)
	if !ok {
		fmt.Fprintf(os.Stderr, "[architex] error: --repo must be \"owner/name\", got %q\n", *repo)
		return 2
	}
	if *prNum <= 0 {
		fmt.Fprintln(os.Stderr, "[architex] error: --pr must be a positive integer")
		return 2
	}
	if *mode != "advisory" && *mode != "blocking" {
		fmt.Fprintf(os.Stderr, "[architex] error: --mode must be \"advisory\" or \"blocking\", got %q\n", *mode)
		return 2
	}

	bodyPath := filepath.Join(bundleDir, "summary.md")
	scorePath := filepath.Join(bundleDir, "score.json")

	body, err := os.ReadFile(bodyPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error reading %s: %v\n", bodyPath, err)
		return 1
	}
	scoreRaw, err := os.ReadFile(scorePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error reading %s: %v\n", scorePath, err)
		return 1
	}
	var result risk.RiskResult
	if err := json.Unmarshal(scoreRaw, &result); err != nil {
		fmt.Fprintf(os.Stderr, "[architex] error parsing %s: %v\n", scorePath, err)
		return 1
	}

	originalBytes := len(body)
	body = capCommentBody(body, commentBodyBudget)
	if len(body) != originalBytes {
		fmt.Fprintf(os.Stderr, "[architex] body safety net engaged: %d bytes -> %d bytes (diagram block stripped)\n",
			originalBytes, len(body))
	}

	fmt.Fprintf(os.Stderr, "[architex] sticky-upserting comment on %s/%s#%d (mode=%s, status=%s, body=%d bytes)\n",
		owner, repoName, *prNum, *mode, result.Status, len(body))

	if *dryRun {
		fmt.Fprintf(os.Stderr, "[architex] dry-run: would POST/PATCH a %d-byte body containing marker=%v\n",
			len(body), strings.Contains(string(body), stickyMarker))
	} else {
		token := os.Getenv(*tokenEnv)
		if token == "" {
			fmt.Fprintf(os.Stderr, "[architex] error: %s is empty -- pass a token via --token-env or set the env var\n", *tokenEnv)
			return 1
		}
		client := gh.New(token)
		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		defer cancel()
		comment, err := gh.UpsertStickyComment(ctx, client, owner, repoName, *prNum, stickyMarker, string(body))
		if err != nil {
			fmt.Fprintf(os.Stderr, "[architex] error: %v\n", err)
			return 1
		}
		fmt.Fprintf(os.Stderr, "[architex] comment id=%d url=%s\n", comment.ID, comment.URL)
	}

	if *mode == "blocking" && result.Status == "fail" {
		fmt.Fprintln(os.Stderr, "[architex] blocking mode: exiting 1 due to risk.Status=fail")
		return 1
	}
	return 0
}

// splitRepoSlug parses an "owner/name" repository slug. The split is
// SplitN(slug, "/", 2) so a slug like "org/group/repo" maps to
// ("org", "group/repo", true) -- callers (the GitHub API) treat the
// second token as a repository name verbatim.
func splitRepoSlug(slug string) (owner, name string, ok bool) {
	parts := strings.SplitN(slug, "/", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", false
	}
	return parts[0], parts[1], true
}

// capCommentBody enforces an upper byte bound on the PR-comment body. If
// body is already within budget it is returned unchanged. Otherwise the
// strategy is:
//
//  1. Locate the fenced ```mermaid ... ``` block (the largest section by far
//     for big deltas) and replace it with a one-line note pointing at the
//     audit bundle artifact.
//  2. If that already fits, return.
//  3. If still oversize (or no mermaid block existed), hard-truncate at
//     maxBytes-128 bytes and append an explicit truncation marker so the
//     comment never claims to be complete when it isn't.
//
// The note and marker are deterministic; the sticky marker (footer) MUST
// remain present in the result so the next run can find and update this
// same comment in place.
func capCommentBody(body []byte, maxBytes int) []byte {
	if maxBytes <= 0 || len(body) <= maxBytes {
		return body
	}

	const mermaidOpen = "```mermaid"
	const mermaidClose = "```"
	noticeFmt := "_Diagram omitted: rendered comment was %d bytes (over the %d-byte safety budget). Full diagram is in the ArchiteX audit bundle artifact._\n"

	if openIdx := bytes.Index(body, []byte(mermaidOpen)); openIdx >= 0 {
		closeRel := bytes.Index(body[openIdx+len(mermaidOpen):], []byte(mermaidClose))
		if closeRel >= 0 {
			closeIdx := openIdx + len(mermaidOpen) + closeRel + len(mermaidClose)
			if closeIdx < len(body) && body[closeIdx] == '\n' {
				closeIdx++
			}
			notice := []byte(fmt.Sprintf(noticeFmt, len(body), maxBytes))
			rebuilt := make([]byte, 0, len(body)-(closeIdx-openIdx)+len(notice))
			rebuilt = append(rebuilt, body[:openIdx]...)
			rebuilt = append(rebuilt, notice...)
			rebuilt = append(rebuilt, body[closeIdx:]...)
			if len(rebuilt) <= maxBytes {
				return rebuilt
			}
			body = rebuilt
		}
	}

	// Hard fallback: truncate while keeping the sticky marker so future runs
	// can still find this comment and update it in place.
	const truncationTag = "\n\n_[ArchiteX comment truncated to fit GitHub size limit -- see audit bundle artifact for the full report.]_\n" + stickyMarker + "\n"
	keep := maxBytes - len(truncationTag)
	if keep < 0 {
		keep = 0
	}
	if keep > len(body) {
		keep = len(body)
	}
	out := make([]byte, 0, keep+len(truncationTag))
	out = append(out, body[:keep]...)
	out = append(out, []byte(truncationTag)...)
	return out
}
