package cli

import (
	"bytes"
	"strings"
	"testing"
)

// makeOversizedBody builds a synthetic summary.md mimicking the shape
// produced by interpreter.FormatMarkdown: a small prologue, a large fenced
// ```mermaid block, a small policy footer, and the sticky marker. We
// control the mermaid-block byte size precisely via the totalSize argument.
func makeOversizedBody(totalSize int) []byte {
	var b bytes.Buffer
	b.WriteString("## [FAIL] Risk Level: HIGH\n\n## Plain-English Summary\n\nA stress-test summary.\n\n")
	b.WriteString("## Delta Diagram\n\n```mermaid\nflowchart LR\n")
	for b.Len() < totalSize-200 {
		b.WriteString("    aws_lb_xx[\"+ entry_point: aws_lb.xx\"]:::added\n")
	}
	b.WriteString("```\n\n## Policy Result\n\n- a finding\n\n---\n_Generated by ArchiteX (deterministic mode)._\n")
	return b.Bytes()
}

func TestCapCommentBody_UnderBudgetReturnedUnchanged(t *testing.T) {
	body := makeOversizedBody(5_000)
	out := capCommentBody(body, 240_000)
	if !bytes.Equal(body, out) {
		t.Errorf("under-budget body should be returned unchanged (in=%d, out=%d)", len(body), len(out))
	}
}

func TestCapCommentBody_StripsMermaidBlockWhenOversized(t *testing.T) {
	body := makeOversizedBody(300_000)
	out := capCommentBody(body, 240_000)

	if len(out) > 240_000 {
		t.Errorf("capped body is %d bytes, want <= 240,000", len(out))
	}
	if bytes.Contains(out, []byte("```mermaid")) {
		t.Errorf("capped body still contains a mermaid fence:\n%s", string(out)[:500])
	}
	if !bytes.Contains(out, []byte("Diagram omitted")) {
		t.Errorf("capped body must announce the omission, got:\n%s", string(out)[:500])
	}
	if !bytes.Contains(out, []byte(stickyMarker)) {
		t.Errorf("capped body must preserve the sticky marker so future runs can find it")
	}
	if !bytes.Contains(out, []byte("## Policy Result")) {
		t.Errorf("capped body must preserve sections that come after the diagram")
	}
}

func TestCapCommentBody_HardTruncationFallback(t *testing.T) {
	// Pathological case: no mermaid block but body is huge.
	huge := []byte(strings.Repeat("A", 500_000) + "\n" + stickyMarker + "\n")
	out := capCommentBody(huge, 240_000)
	if len(out) > 240_000 {
		t.Errorf("hard-truncated body is %d bytes, want <= 240,000", len(out))
	}
	if !bytes.Contains(out, []byte("comment truncated")) {
		t.Errorf("hard truncation must announce itself, got tail:\n%s", string(out[len(out)-300:]))
	}
	if !bytes.Contains(out, []byte(stickyMarker)) {
		t.Errorf("hard-truncated body must end with the sticky marker for upsert continuity")
	}
}

func TestCapCommentBody_BudgetZeroMeansNoCap(t *testing.T) {
	body := makeOversizedBody(300_000)
	out := capCommentBody(body, 0)
	if !bytes.Equal(body, out) {
		t.Errorf("budget 0 should mean no cap, expected unchanged body")
	}
}

func TestSplitRepoSlug(t *testing.T) {
	cases := []struct {
		in    string
		owner string
		name  string
		ok    bool
	}{
		{"acme/widgets", "acme", "widgets", true},
		{"acme/", "", "", false},
		{"/widgets", "", "", false},
		{"no-slash", "", "", false},
		{"", "", "", false},
		{"a/b/c", "a", "b/c", true}, // SplitN(slug, "/", 2) keeps the rest
	}
	for _, c := range cases {
		owner, name, ok := splitRepoSlug(c.in)
		if owner != c.owner || name != c.name || ok != c.ok {
			t.Errorf("splitRepoSlug(%q) = (%q, %q, %v); want (%q, %q, %v)",
				c.in, owner, name, ok, c.owner, c.name, c.ok)
		}
	}
}
