package github

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
)

const testMarker = "_Generated by ArchiteX (deterministic mode)._"

func newTestClient(t *testing.T, h http.HandlerFunc) (*Client, *httptest.Server) {
	t.Helper()
	srv := httptest.NewServer(h)
	t.Cleanup(srv.Close)
	c := New("test-token")
	c.BaseURL = srv.URL
	return c, srv
}

func TestUpsertStickyComment_CreatesWhenAbsent(t *testing.T) {
	var listed, created, updated int32
	c, _ := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == http.MethodGet && strings.Contains(r.URL.Path, "/issues/42/comments"):
			atomic.AddInt32(&listed, 1)
			writeJSON(t, w, []Comment{{ID: 1, Body: "unrelated chatter"}})
		case r.Method == http.MethodPost && strings.HasSuffix(r.URL.Path, "/issues/42/comments"):
			atomic.AddInt32(&created, 1)
			body := decodeBody(t, r)
			if !strings.Contains(body, testMarker) {
				t.Fatalf("posted body missing marker: %q", body)
			}
			writeJSON(t, w, Comment{ID: 99, Body: body, URL: "https://example/c/99"})
		case r.Method == http.MethodPatch:
			atomic.AddInt32(&updated, 1)
			t.Fatalf("unexpected PATCH when no existing sticky comment present")
		default:
			t.Fatalf("unexpected request: %s %s", r.Method, r.URL.Path)
		}
	})

	body := "hello world\n\n" + testMarker + "\n"
	got, err := UpsertStickyComment(context.Background(), c, "o", "r", 42, testMarker, body)
	if err != nil {
		t.Fatalf("UpsertStickyComment: %v", err)
	}
	if got.ID != 99 {
		t.Fatalf("got comment id %d, want 99", got.ID)
	}
	if listed != 1 || created != 1 || updated != 0 {
		t.Fatalf("call counts: listed=%d created=%d updated=%d", listed, created, updated)
	}
}

func TestUpsertStickyComment_UpdatesExisting(t *testing.T) {
	var created, updated int32
	c, _ := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == http.MethodGet:
			writeJSON(t, w, []Comment{
				{ID: 1, Body: "unrelated"},
				{ID: 2, Body: "stale architex report\n" + testMarker},
				{ID: 3, Body: "even more chatter"},
			})
		case r.Method == http.MethodPatch && strings.HasSuffix(r.URL.Path, "/issues/comments/2"):
			atomic.AddInt32(&updated, 1)
			body := decodeBody(t, r)
			if !strings.Contains(body, "fresh") {
				t.Fatalf("patched body missing 'fresh': %q", body)
			}
			writeJSON(t, w, Comment{ID: 2, Body: body})
		case r.Method == http.MethodPost:
			atomic.AddInt32(&created, 1)
			t.Fatalf("unexpected POST when existing sticky comment present")
		default:
			t.Fatalf("unexpected request: %s %s", r.Method, r.URL.Path)
		}
	})

	body := "fresh report\n" + testMarker
	got, err := UpsertStickyComment(context.Background(), c, "o", "r", 7, testMarker, body)
	if err != nil {
		t.Fatalf("UpsertStickyComment: %v", err)
	}
	if got.ID != 2 {
		t.Fatalf("got id %d, want 2 (the marker-bearing comment)", got.ID)
	}
	if created != 0 || updated != 1 {
		t.Fatalf("call counts: created=%d updated=%d", created, updated)
	}
}

func TestUpsertStickyComment_FollowsPagination(t *testing.T) {
	var page int32
	c, _ := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPatch {
			writeJSON(t, w, Comment{ID: 555, Body: decodeBody(t, r)})
			return
		}
		if r.Method != http.MethodGet {
			t.Fatalf("unexpected method %s", r.Method)
		}
		switch atomic.AddInt32(&page, 1) {
		case 1:
			// Build the next-page URL from the inbound request so the
			// client follows it back to the same test server.
			next := fmt.Sprintf("http://%s/repos/o/r/issues/9/comments?page=2", r.Host)
			w.Header().Set("Link", fmt.Sprintf(`<%s>; rel="next"`, next))
			writeJSON(t, w, []Comment{{ID: 100, Body: "page1 noise"}})
		case 2:
			writeJSON(t, w, []Comment{
				{ID: 200, Body: "page2 chatter"},
				{ID: 555, Body: "old report\n" + testMarker},
			})
		default:
			t.Fatalf("unexpected extra page request")
		}
	})

	body := "new report\n" + testMarker
	got, err := UpsertStickyComment(context.Background(), c, "o", "r", 9, testMarker, body)
	if err != nil {
		t.Fatalf("UpsertStickyComment: %v", err)
	}
	if got.ID != 555 {
		t.Fatalf("got id %d, want 555", got.ID)
	}
	if page != 2 {
		t.Fatalf("expected 2 list pages, got %d", page)
	}
}

func TestClient_AuthorizationAndHeaders(t *testing.T) {
	c, _ := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		if got := r.Header.Get("Authorization"); got != "Bearer test-token" {
			t.Fatalf("Authorization header = %q, want Bearer test-token", got)
		}
		if got := r.Header.Get("Accept"); got != acceptHeader {
			t.Fatalf("Accept header = %q, want %q", got, acceptHeader)
		}
		if got := r.Header.Get("X-GitHub-Api-Version"); got != apiVersion {
			t.Fatalf("X-GitHub-Api-Version = %q, want %q", got, apiVersion)
		}
		if got := r.Header.Get("User-Agent"); got != userAgent {
			t.Fatalf("User-Agent = %q, want %q", got, userAgent)
		}
		writeJSON(t, w, []Comment{})
	})

	if _, err := c.ListIssueComments(context.Background(), "o", "r", 1); err != nil {
		t.Fatalf("ListIssueComments: %v", err)
	}
}

func TestUpsertStickyComment_RefusesEmptyMarker(t *testing.T) {
	c := New("")
	_, err := UpsertStickyComment(context.Background(), c, "o", "r", 1, "", "anything")
	if err == nil || !strings.Contains(err.Error(), "empty sticky marker") {
		t.Fatalf("expected empty-marker error, got %v", err)
	}
}

func TestUpsertStickyComment_RefusesBodyWithoutMarker(t *testing.T) {
	c := New("")
	_, err := UpsertStickyComment(context.Background(), c, "o", "r", 1, testMarker, "no marker here")
	if err == nil || !strings.Contains(err.Error(), "does not contain sticky marker") {
		t.Fatalf("expected missing-marker-in-body error, got %v", err)
	}
}

func TestClient_NonSuccessReturnsError(t *testing.T) {
	c, _ := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusUnprocessableEntity)
		_, _ = w.Write([]byte(`{"message":"Validation Failed"}`))
	})
	_, err := c.CreateIssueComment(context.Background(), "o", "r", 1, "body\n"+testMarker)
	if err == nil || !strings.Contains(err.Error(), "HTTP 422") {
		t.Fatalf("expected HTTP 422 error, got %v", err)
	}
}

func TestParseNextLink(t *testing.T) {
	cases := []struct {
		header string
		want   string
	}{
		{"", ""},
		{`<https://api.github.com/x?page=2>; rel="next", <https://api.github.com/x?page=5>; rel="last"`, "https://api.github.com/x?page=2"},
		{`<https://api.github.com/x?page=1>; rel="prev", <https://api.github.com/x?page=3>; rel="next"`, "https://api.github.com/x?page=3"},
		{`<https://api.github.com/x?page=5>; rel="last"`, ""},
	}
	for _, tc := range cases {
		if got := parseNextLink(tc.header); got != tc.want {
			t.Errorf("parseNextLink(%q) = %q, want %q", tc.header, got, tc.want)
		}
	}
}

// --- helpers -------------------------------------------------------------

func writeJSON(t *testing.T, w http.ResponseWriter, v any) {
	t.Helper()
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(v); err != nil {
		t.Fatalf("encode: %v", err)
	}
}

func decodeBody(t *testing.T, r *http.Request) string {
	t.Helper()
	raw, err := io.ReadAll(r.Body)
	if err != nil {
		t.Fatalf("read req body: %v", err)
	}
	var got struct {
		Body string `json:"body"`
	}
	if err := json.Unmarshal(raw, &got); err != nil {
		t.Fatalf("decode req body: %v", err)
	}
	return got.Body
}
