package interpreter

import (
	"fmt"
	"strings"

	"architex/risk"
)

// FormatMarkdown renders a Report as the five-section PR comment described in
// master.md §10.1. The structure is fixed -- empty sections still render with
// an explicit "no findings" line so the comment shape is stable across PRs.
func FormatMarkdown(rep Report) string {
	var b strings.Builder

	b.WriteString(renderRiskBanner(rep.Risk))
	b.WriteString("\n")
	b.WriteString("## Plain-English Summary\n\n")
	b.WriteString(rep.Summary)
	b.WriteString("\n\n")

	b.WriteString("## Suggested Review Focus\n\n")
	if len(rep.ReviewFocus) == 0 {
		b.WriteString("- No specific review focus suggested.\n")
	} else {
		for _, f := range rep.ReviewFocus {
			fmt.Fprintf(&b, "- %s\n", f)
		}
	}
	b.WriteString("\n")

	b.WriteString("## Delta Diagram\n\n")
	if strings.TrimSpace(rep.Diagram) == "" {
		b.WriteString("_No diagram available._\n\n")
	} else {
		b.WriteString("```mermaid\n")
		b.WriteString(rep.Diagram)
		if !strings.HasSuffix(rep.Diagram, "\n") {
			b.WriteString("\n")
		}
		b.WriteString("```\n\n")
	}

	b.WriteString(renderPolicySection(rep.Risk))
	b.WriteString("\n")
	if section := renderSuppressionsSection(rep.Risk); section != "" {
		b.WriteString(section)
		b.WriteString("\n")
	}
	b.WriteString("---\n")
	b.WriteString("_Generated by ArchiteX (deterministic mode)._\n")

	return b.String()
}

func renderRiskBanner(r risk.RiskResult) string {
	icon := "[OK]"
	switch r.Status {
	case "warn":
		icon = "[WARN]"
	case "fail":
		icon = "[FAIL]"
	}
	return fmt.Sprintf(
		"## %s Risk Level: %s (%.1f/10 &mdash; higher means more risk)\n\nStatus: **%s** &middot; Severity: **%s**\n",
		icon,
		strings.ToUpper(r.Severity),
		r.Score,
		r.Status,
		r.Severity,
	)
}

// renderSuppressionsSection emits an audit footer listing every rule that was
// silenced by a `.architex.yml` entry or an inline `# architex:ignore=...`
// comment. It returns the empty string when there are no suppressions so the
// PR comment shape stays unchanged for zero-config repos.
//
// Expired suppressions are flagged inline (`(EXPIRED)`) so reviewers can
// spot a stale ignore that someone forgot to refresh -- they still drop the
// risk reason for backwards compatibility, but the visibility is intentional.
func renderSuppressionsSection(r risk.RiskResult) string {
	if len(r.Suppressed) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("## Suppressed Findings\n\n")
	fmt.Fprintf(&b, "_%d finding(s) silenced by config or inline directives. They are excluded from the score above._\n\n",
		len(r.Suppressed))
	for _, s := range r.Suppressed {
		expiredTag := ""
		if s.Expired {
			expiredTag = " *(EXPIRED — please refresh or remove)*"
		}
		reason := s.Reason
		if reason == "" {
			reason = "(no reason supplied)"
		}
		source := s.Source
		if source == "" {
			source = "config"
		}
		fmt.Fprintf(&b, "- `%s` on `%s` &mdash; %s &middot; _%s_%s\n",
			s.RuleID,
			s.ResourceID,
			reason,
			source,
			expiredTag,
		)
	}
	return b.String()
}

func renderPolicySection(r risk.RiskResult) string {
	var b strings.Builder
	b.WriteString("## Policy Result\n\n")
	if len(r.Reasons) == 0 {
		b.WriteString("- No policy violations triggered.\n")
		return b.String()
	}
	for _, reason := range r.Reasons {
		fmt.Fprintf(&b, "- **[%s]** `%s` (weight %.1f) &mdash; %s\n",
			strings.ToUpper(reason.Impact),
			reason.RuleID,
			reason.Weight,
			reason.Message,
		)
	}
	return b.String()
}
