package interpreter

import (
	"fmt"
	"sort"
	"strings"

	"architex/delta"
	"architex/risk"
)

// FormatMarkdown renders a Report as the five-section PR comment described in
// master.md §10.1. The structure is fixed -- empty sections still render with
// an explicit "no findings" line so the comment shape is stable across PRs.
func FormatMarkdown(rep Report) string {
	var b strings.Builder

	b.WriteString(renderRiskBanner(rep.Risk))
	if banner := renderProviderBanner(rep); banner != "" {
		b.WriteString(banner)
	}
	b.WriteString("\n")
	b.WriteString("## Plain-English Summary\n\n")
	b.WriteString(rep.Summary)
	b.WriteString("\n\n")

	b.WriteString("## Suggested Review Focus\n\n")
	if len(rep.ReviewFocus) == 0 {
		b.WriteString("- No specific review focus suggested.\n")
	} else {
		for _, f := range rep.ReviewFocus {
			fmt.Fprintf(&b, "- %s\n", f)
		}
	}
	b.WriteString("\n")

	b.WriteString("## Delta Diagram\n\n")
	if strings.TrimSpace(rep.Diagram) == "" {
		b.WriteString("_No diagram available._\n\n")
	} else {
		b.WriteString("```mermaid\n")
		b.WriteString(rep.Diagram)
		if !strings.HasSuffix(rep.Diagram, "\n") {
			b.WriteString("\n")
		}
		b.WriteString("```\n\n")
	}

	b.WriteString(renderPolicySection(rep.Risk))
	b.WriteString("\n")
	if section := renderSuppressionsSection(rep.Risk); section != "" {
		b.WriteString(section)
		b.WriteString("\n")
	}
	b.WriteString("---\n")
	b.WriteString("_Generated by ArchiteX (deterministic mode)._\n")

	return b.String()
}

// renderProviderBanner is a Phase 9 (v1.4) cosmetic line that names the
// IaC providers ArchiteX recognized in the head graph. It is purely
// informational: it does NOT affect the score, the egress payload, the
// risk reasons, or the Mermaid diagram. The output is deterministic --
// providers are extracted from the prefix before the first underscore in
// each Node.ProviderType, deduplicated, and sorted alphabetically.
//
// Two data sources, in order of preference:
//
//  1. rep.Providers / rep.ResourceCount populated by RenderWithGraph
//     (v1.4+). This describes the WHOLE head repository, which is what a
//     reviewer of a hybrid-cloud PR actually wants -- "your repo has
//     aws + azurerm" -- not "this PR happened to touch only azurerm".
//
//  2. Fallback to the delta when Providers is empty (graph-less Render).
//     This preserves bit-identical behavior for any pre-v1.4 caller and
//     keeps the existing tests / fixtures green.
//
// In either case, an empty result returns the empty string so empty PRs
// never carry a misleading banner.
func renderProviderBanner(rep Report) string {
	if len(rep.Providers) > 0 && rep.ResourceCount > 0 {
		noun := "resources"
		if rep.ResourceCount == 1 {
			noun = "resource"
		}
		return fmt.Sprintf("\n_Detected providers: %s &mdash; %d %s analyzed._\n",
			strings.Join(rep.Providers, ", "), rep.ResourceCount, noun)
	}
	return renderProviderBannerFromDelta(rep.Delta)
}

// renderProviderBannerFromDelta is the legacy / fallback path used when
// the caller did not supply a head graph. It reports providers seen in
// the delta only -- accurate but narrower -- and is kept exclusively for
// backward compatibility with graph-less Render callers.
func renderProviderBannerFromDelta(d delta.Delta) string {
	seen := map[string]bool{}
	count := 0
	collect := func(provType string) {
		if provType == "" {
			return
		}
		count++
		i := strings.IndexByte(provType, '_')
		var prefix string
		if i <= 0 {
			prefix = provType
		} else {
			prefix = provType[:i]
		}
		seen[prefix] = true
	}
	for _, n := range d.AddedNodes {
		collect(n.ProviderType)
	}
	for _, n := range d.RemovedNodes {
		collect(n.ProviderType)
	}
	for _, cn := range d.ChangedNodes {
		collect(cn.ProviderType)
	}
	if count == 0 {
		return ""
	}
	providers := make([]string, 0, len(seen))
	for p := range seen {
		providers = append(providers, p)
	}
	sort.Strings(providers)
	noun := "resources"
	if count == 1 {
		noun = "resource"
	}
	return fmt.Sprintf("\n_Detected providers: %s &mdash; %d %s analyzed._\n",
		strings.Join(providers, ", "), count, noun)
}

func renderRiskBanner(r risk.RiskResult) string {
	icon := "[OK]"
	switch r.Status {
	case "warn":
		icon = "[WARN]"
	case "fail":
		icon = "[FAIL]"
	}
	return fmt.Sprintf(
		"## %s Risk Level: %s (%.1f/10 &mdash; higher means more risk)\n\nStatus: **%s** &middot; Severity: **%s**\n",
		icon,
		strings.ToUpper(r.Severity),
		r.Score,
		r.Status,
		r.Severity,
	)
}

// renderSuppressionsSection emits an audit footer listing every rule that was
// silenced by a `.architex.yml` entry or an inline `# architex:ignore=...`
// comment. It returns the empty string when there are no suppressions so the
// PR comment shape stays unchanged for zero-config repos.
//
// Expired suppressions are flagged inline (`(EXPIRED)`) so reviewers can
// spot a stale ignore that someone forgot to refresh -- they still drop the
// risk reason for backwards compatibility, but the visibility is intentional.
func renderSuppressionsSection(r risk.RiskResult) string {
	if len(r.Suppressed) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("## Suppressed Findings\n\n")
	fmt.Fprintf(&b, "_%d finding(s) silenced by config or inline directives. They are excluded from the score above._\n\n",
		len(r.Suppressed))
	for _, s := range r.Suppressed {
		expiredTag := ""
		if s.Expired {
			expiredTag = " *(EXPIRED — please refresh or remove)*"
		}
		reason := s.Reason
		if reason == "" {
			reason = "(no reason supplied)"
		}
		source := s.Source
		if source == "" {
			source = "config"
		}
		fmt.Fprintf(&b, "- `%s` on `%s` &mdash; %s &middot; _%s_%s\n",
			s.RuleID,
			s.ResourceID,
			reason,
			source,
			expiredTag,
		)
	}
	return b.String()
}

func renderPolicySection(r risk.RiskResult) string {
	var b strings.Builder
	b.WriteString("## Policy Result\n\n")
	if len(r.Reasons) == 0 {
		b.WriteString("- No policy violations triggered.\n")
		return b.String()
	}
	for _, reason := range r.Reasons {
		fmt.Fprintf(&b, "- **[%s]** `%s` (weight %.1f) &mdash; %s\n",
			strings.ToUpper(reason.Impact),
			reason.RuleID,
			reason.Weight,
			reason.Message,
		)
	}
	return b.String()
}
