package interpreter

import (
	"strings"
	"testing"

	"architex/delta"
	"architex/models"
	"architex/risk"
)

func TestFormatMarkdown_AllFiveSectionsPresent(t *testing.T) {
	d := highRiskDelta()
	r := runRisk(d)
	rep := Render(d, r, nil)
	md := FormatMarkdown(rep)

	mustContain := []string{
		"## [FAIL] Risk Level: HIGH (9.0/10 &mdash; higher means more risk)",
		"## Plain-English Summary",
		"## Suggested Review Focus",
		"## Delta Diagram",
		"```mermaid",
		"## Policy Result",
		"public_exposure_introduced",
		"_Generated by ArchiteX (deterministic mode)._",
	}
	for _, want := range mustContain {
		if !strings.Contains(md, want) {
			t.Errorf("missing section/text %q in:\n%s", want, md)
		}
	}
}

func TestFormatMarkdown_EmptyDeltaProducesStableShape(t *testing.T) {
	d := emptyDelta()
	r := runRisk(d)
	rep := Render(d, r, nil)
	md := FormatMarkdown(rep)

	// All five section headers must still be present even with no findings.
	for _, h := range []string{
		"## Plain-English Summary",
		"## Suggested Review Focus",
		"## Delta Diagram",
		"## Policy Result",
	} {
		if !strings.Contains(md, h) {
			t.Errorf("missing header %q in empty-delta markdown:\n%s", h, md)
		}
	}
	if !strings.Contains(md, "No policy violations triggered.") {
		t.Errorf("expected empty-policy fallback line, got:\n%s", md)
	}
}

func TestFormatMarkdown_BannerStatusReflectsRisk(t *testing.T) {
	cases := []struct {
		name       string
		delta      func() interface{}
		wantBanner string
		wantStatus string
	}{
		{"high", nil, "[FAIL]", "**fail**"},
		{"medium", nil, "[WARN]", "**warn**"},
		{"low", nil, "[OK]", "**pass**"},
	}

	highRep := Render(highRiskDelta(), runRisk(highRiskDelta()), nil)
	dbRep := Render(dbAddedDelta(), runRisk(dbAddedDelta()), nil)
	emptyRep := Render(emptyDelta(), runRisk(emptyDelta()), nil)

	if got := FormatMarkdown(highRep); !strings.Contains(got, cases[0].wantBanner) || !strings.Contains(got, cases[0].wantStatus) {
		t.Errorf("high-risk banner mismatch:\n%s", got)
	}
	// dbAdded scores 2.5 -> low/pass, not medium. Use a synthetic medium fixture
	// would require constructing a 3.0+ delta; instead assert the boundary
	// behavior we have.
	if got := FormatMarkdown(dbRep); !strings.Contains(got, "Risk Level: LOW") || !strings.Contains(got, "**pass**") {
		t.Errorf("db-added banner should be LOW/pass, got:\n%s", got)
	}
	if got := FormatMarkdown(emptyRep); !strings.Contains(got, "[OK]") || !strings.Contains(got, "**pass**") {
		t.Errorf("empty banner should be OK/pass, got:\n%s", got)
	}
}

func TestFormatMarkdown_NoSuppressionsSection_WhenEmpty(t *testing.T) {
	rep := Render(highRiskDelta(), runRisk(highRiskDelta()), nil)
	md := FormatMarkdown(rep)
	if strings.Contains(md, "## Suppressed Findings") {
		t.Errorf("suppressions section must be omitted when none, got:\n%s", md)
	}
}

func TestFormatMarkdown_SuppressionsSection_RendersListAndExpiryFlag(t *testing.T) {
	d := highRiskDelta()
	r := runRisk(d)
	r.Suppressed = []risk.SuppressedFinding{
		{
			RuleID:     "s3_bucket_public_exposure",
			ResourceID: "aws_s3_bucket.public_assets",
			Reason:     "intentionally public docs site",
			Source:     "config:.architex.yml",
		},
		{
			RuleID:     "iam_admin_policy_attached",
			ResourceID: "aws_iam_role_policy_attachment.bootstrap",
			Reason:     "bootstrap-only role; tracked in JIRA-99",
			Source:     "inline:infra/main.tf:42",
			Expired:    true,
		},
	}
	rep := Render(d, r, nil)
	md := FormatMarkdown(rep)
	mustContain := []string{
		"## Suppressed Findings",
		"2 finding(s) silenced",
		"`s3_bucket_public_exposure` on `aws_s3_bucket.public_assets`",
		"intentionally public docs site",
		"config:.architex.yml",
		"`iam_admin_policy_attached` on `aws_iam_role_policy_attachment.bootstrap`",
		"inline:infra/main.tf:42",
		"*(EXPIRED",
	}
	for _, want := range mustContain {
		if !strings.Contains(md, want) {
			t.Errorf("missing %q in suppressions section:\n%s", want, md)
		}
	}
	idxSuppressed := strings.Index(md, "## Suppressed Findings")
	idxFooter := strings.Index(md, "_Generated by ArchiteX")
	if idxSuppressed < 0 || idxFooter < 0 || idxSuppressed > idxFooter {
		t.Errorf("suppressions section must appear before sticky footer; got idxSuppressed=%d idxFooter=%d", idxSuppressed, idxFooter)
	}
}

// TestFormatMarkdown_ProviderBanner_SingleProvider locks in the v1.4
// "Detected providers" cosmetic line for the existing AWS-only PR shape.
// The banner must appear, name "aws", and report the count.
func TestFormatMarkdown_ProviderBanner_SingleProvider(t *testing.T) {
	rep := Render(highRiskDelta(), runRisk(highRiskDelta()), nil)
	md := FormatMarkdown(rep)
	if !strings.Contains(md, "_Detected providers: aws &mdash;") {
		t.Errorf("expected single-provider banner naming aws, got:\n%s", md)
	}
}

// TestFormatMarkdown_ProviderBanner_MultipleProviders verifies the
// alphabetical, deduplicated, comma-joined output when both aws and
// azurerm appear in a single PR.
func TestFormatMarkdown_ProviderBanner_MultipleProviders(t *testing.T) {
	d := delta.Delta{
		AddedNodes: []models.Node{
			{ID: "aws_lb.web", Type: "entry_point", ProviderType: "aws_lb"},
			{ID: "azurerm_lb.front", Type: "entry_point", ProviderType: "azurerm_lb"},
			// Duplicate to assert dedup.
			{ID: "azurerm_storage_account.data", Type: "storage", ProviderType: "azurerm_storage_account"},
		},
		Summary: delta.DeltaSummary{AddedNodes: 3},
	}
	rep := Render(d, runRisk(d), nil)
	md := FormatMarkdown(rep)
	if !strings.Contains(md, "_Detected providers: aws, azurerm &mdash; 3 resources analyzed._") {
		t.Errorf("expected dedup'd alphabetical multi-provider banner with count, got:\n%s", md)
	}
}

// TestFormatMarkdown_ProviderBanner_OmittedOnZeroNodes documents the
// graceful degradation: an edge-only or empty delta produces no banner
// (the existing comment shape is preserved for that path).
func TestFormatMarkdown_ProviderBanner_OmittedOnZeroNodes(t *testing.T) {
	rep := Render(emptyDelta(), runRisk(emptyDelta()), nil)
	md := FormatMarkdown(rep)
	if strings.Contains(md, "Detected providers:") {
		t.Errorf("banner must be omitted on zero-node delta, got:\n%s", md)
	}
}

// TestFormatMarkdown_ProviderBanner_RepoWideViaRenderWithGraph locks in
// the v1.4 fix for hybrid-cloud PRs: when the head graph is supplied,
// the banner must describe the WHOLE repo (including unchanged AWS
// resources alongside an Azure subsystem the PR adds), not just the
// providers that happen to appear in the delta. This is the exact
// "AWS base + AWS preserved + Azure added" scenario validated against
// architex-test-customer.
func TestFormatMarkdown_ProviderBanner_RepoWideViaRenderWithGraph(t *testing.T) {
	d := delta.Delta{
		AddedNodes: []models.Node{
			{ID: "azurerm_lb.web", Type: "entry_point", ProviderType: "azurerm_lb"},
		},
		Summary: delta.DeltaSummary{AddedNodes: 1},
	}
	head := models.Graph{
		Nodes: []models.Node{
			{ID: "aws_vpc.main", Type: "network", ProviderType: "aws_vpc"},
			{ID: "aws_subnet.public", Type: "network", ProviderType: "aws_subnet"},
			{ID: "azurerm_lb.web", Type: "entry_point", ProviderType: "azurerm_lb"},
		},
	}
	rep := RenderWithGraph(d, runRisk(d), head, nil)
	md := FormatMarkdown(rep)
	if !strings.Contains(md, "_Detected providers: aws, azurerm &mdash; 3 resources analyzed._") {
		t.Errorf("expected repo-wide banner naming both aws and azurerm with total head count, got:\n%s", md)
	}
}

// TestFormatMarkdown_ProviderBanner_RenderFallsBackToDelta pins the
// backward-compat contract: the legacy three-arg Render(d, r, interp)
// path (no head graph) MUST keep emitting the delta-derived banner so
// existing callers and the v1.4 unit tests above stay bit-identical.
func TestFormatMarkdown_ProviderBanner_RenderFallsBackToDelta(t *testing.T) {
	d := delta.Delta{
		AddedNodes: []models.Node{
			{ID: "azurerm_lb.web", Type: "entry_point", ProviderType: "azurerm_lb"},
		},
		Summary: delta.DeltaSummary{AddedNodes: 1},
	}
	rep := Render(d, runRisk(d), nil)
	md := FormatMarkdown(rep)
	if !strings.Contains(md, "_Detected providers: azurerm &mdash; 1 resource analyzed._") {
		t.Errorf("expected delta-fallback banner from graph-less Render, got:\n%s", md)
	}
}

func TestFormatMarkdown_DiagramWrappedInMermaidFence(t *testing.T) {
	rep := Render(highRiskDelta(), runRisk(highRiskDelta()), nil)
	md := FormatMarkdown(rep)
	if !strings.Contains(md, "```mermaid\nflowchart LR") {
		t.Errorf("expected diagram wrapped in mermaid fence starting with flowchart LR, got:\n%s", md)
	}
}
